/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package smith.tech;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import smith.tech.Database;

/**
 *
 * @author Samuel
 */
public class Separator extends javax.swing.JFrame {
    
    int currentDB = 0;
    int HOMEOFFICE = 1;
    int DC = 2;
    int CONTRACTOR = 3;
    int STORES = 4;
    int selectedUser = -1;
    String[] hoLoc = new String[] {"C:/ProgramData/Separator/", "ho.csv"};
    String[] dcLoc = new String[] {"C:/ProgramData/Separator/", "dc.csv"};
    String[] storeLoc = new String[] {"C:/ProgramData/Separator/", "store.csv"};
    String[] contLoc = new String[] {"C:/ProgramData/Separator/", "cont.csv"};
    Database dc = new Database(dcLoc);
    Database ho = new Database(hoLoc);
    Database store = new Database(storeLoc);
    Database cont = new Database(contLoc);
    
    /*Purpose: Set unprocessed and unexported items for selected database
    *To Do: Add support for updating different databases
    */
    /**
     * Set unprocessed and unexported items for selected database
     */
    private void updateSingleStats() {
        if (currentDB == HOMEOFFICE)
        {
            singUnProStat.setText(ho.updateProcessed()); //set to number of unprocessed items
            singleUnExStat.setText(ho.updateExported());
        }
        
        else if (currentDB == DC)
        {
            singUnProStat.setText(dc.updateProcessed()); // set to number of unprocessed items
            singleUnExStat.setText(dc.updateExported());
        }
        
        else if (currentDB == CONTRACTOR)
        {
            singUnProStat.setText(cont.updateProcessed()); //set to number of unprocessed items
            singleUnExStat.setText(cont.updateExported());
        }
        
        else if (currentDB == STORES)
        {
            singUnProStat.setText(store.updateProcessed()); //set to number of unprocessed items
            singleUnExStat.setText(store.updateExported());
        }
    }

    /*Purpose: Set total unprocessed and unexported items for selected database
    *To Do: Add the other databases to totals
    */
    /**
     * Set total unprocessed and unexported items for selected database
     */
    private void updateTotStats() {
        int totEx = ho.updateProgressE() +dc.updateProgressE() + store.updateProgressE() + cont.updateProgressE();
        int totPro = ho.updateProgressP() + dc.updateProgressP() + store.updateProgressP() + cont.updateProgressP();
        
        totUnProStat.setText(Integer.toString(totPro));
        totUnExStat.setText(Integer.toString(totEx));
    }
    
    /**
     * Searches through the databases
     * @param filter Criteria to search by
     * @param item Item to search for
     */
    private void searchDB(String filter, String item) {
        ArrayList results = new ArrayList();
        
        if (filter == "User ID") {
            for(int i = 0; i < ho.size(); i++) {
                
            }
        }
    }
    /**
     * Creates new form Separator
     */
    public Separator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rsaProcessor = new javax.swing.JFrame();
        userDisplay = new javax.swing.JFrame();
        jDesktopPane2 = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        openCSV = new javax.swing.JFileChooser();
        openErrorBox = new javax.swing.JDialog();
        dbErrorTitle = new javax.swing.JLabel();
        errorPrompt = new javax.swing.JLabel();
        errorSelect = new javax.swing.JComboBox();
        errorResolve = new javax.swing.JButton();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        dbOverview = new javax.swing.JPanel();
        dbLabel = new javax.swing.JLabel();
        dbSelector = new javax.swing.JComboBox();
        singleUnProUseLabel = new javax.swing.JLabel();
        singUnProStat = new javax.swing.JLabel();
        singleUnExUseLabel = new javax.swing.JLabel();
        singleUnExStat = new javax.swing.JLabel();
        remainingHeader = new javax.swing.JLabel();
        totUnProUseLabel = new javax.swing.JLabel();
        totUnExUseLabel = new javax.swing.JLabel();
        totUnExStat = new javax.swing.JLabel();
        totUnProStat = new javax.swing.JLabel();
        processOverview = new javax.swing.JPanel();
        wpNameLab = new javax.swing.JLabel();
        wpNB = new javax.swing.JButton();
        wpUNLab = new javax.swing.JLabel();
        wpUNB = new javax.swing.JButton();
        attB = new javax.swing.JButton();
        ATTLab = new javax.swing.JLabel();
        notesLab = new javax.swing.JLabel();
        notesB = new javax.swing.JButton();
        rsaLab = new javax.swing.JLabel();
        rsaB = new javax.swing.JButton();
        foldLab = new javax.swing.JLabel();
        foldB = new javax.swing.JButton();
        vmB = new javax.swing.JButton();
        vmLab = new javax.swing.JLabel();
        cmB = new javax.swing.JButton();
        cmLab = new javax.swing.JLabel();
        webLab = new javax.swing.JLabel();
        webB = new javax.swing.JButton();
        rfLab = new javax.swing.JLabel();
        rfB = new javax.swing.JButton();
        skypeLab = new javax.swing.JLabel();
        skypeB = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        search = new javax.swing.JPanel();
        searchLabel = new javax.swing.JLabel();
        searchInput = new javax.swing.JTextField();
        searchBy = new javax.swing.JComboBox();
        searchResult = new javax.swing.JScrollPane();
        searchSelect = new javax.swing.JList();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        openCSVOpt = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();

        javax.swing.GroupLayout rsaProcessorLayout = new javax.swing.GroupLayout(rsaProcessor.getContentPane());
        rsaProcessor.getContentPane().setLayout(rsaProcessorLayout);
        rsaProcessorLayout.setHorizontalGroup(
            rsaProcessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        rsaProcessorLayout.setVerticalGroup(
            rsaProcessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        userDisplay.setTitle("User Info");
        userDisplay.setAlwaysOnTop(true);
        userDisplay.setMinimumSize(new java.awt.Dimension(200, 200));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel1.setText("Samuel Smith");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(140, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel2.setText("Username: samsmit");

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel3.setText("Desk Extension: 4151");

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel4.setText("Email: Samuel_Smith@Abercrombie.com");

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel5.setText("Separation Date: 8/21/2015");

        jLabel6.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel6.setText("CellPhone Number: 216.206.7760");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5))
                    .addComponent(jLabel6))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel7.setText("Not in White Pages (UN)");

        jLabel8.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel8.setText("Not in White Pages (LN)");

        jLabel9.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel9.setText("RSA Removed");

        jLabel10.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel10.setText("No Folder Present");

        jLabel11.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel11.setText("No VM Present");

        jLabel12.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel12.setText("Extension Deleted");

        jLabel13.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel13.setText("Webex Deleted");

        jLabel14.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel14.setText("No RightFax Present");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel14))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(55, 55, 55)
                        .addComponent(jLabel11))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel14))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jDesktopPane2Layout = new javax.swing.GroupLayout(jDesktopPane2);
        jDesktopPane2.setLayout(jDesktopPane2Layout);
        jDesktopPane2Layout.setHorizontalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane2Layout.createSequentialGroup()
                .addGap(0, 353, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jDesktopPane2Layout.createSequentialGroup()
                .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jDesktopPane2Layout.setVerticalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane2Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jDesktopPane2.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jPanel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jPanel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout userDisplayLayout = new javax.swing.GroupLayout(userDisplay.getContentPane());
        userDisplay.getContentPane().setLayout(userDisplayLayout);
        userDisplayLayout.setHorizontalGroup(
            userDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane2)
        );
        userDisplayLayout.setVerticalGroup(
            userDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane2)
        );

        openErrorBox.setAlwaysOnTop(true);
        openErrorBox.setMinimumSize(new java.awt.Dimension(350, 350));

        dbErrorTitle.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        dbErrorTitle.setText("Error! No Database Selected!");

        errorPrompt.setText("Please select database: ");

        errorSelect.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Home Office", "Distribution Center", "Contractors", "Stores" }));
        errorSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                errorSelectActionPerformed(evt);
            }
        });

        errorResolve.setText("Continue");
        errorResolve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                errorResolveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout openErrorBoxLayout = new javax.swing.GroupLayout(openErrorBox.getContentPane());
        openErrorBox.getContentPane().setLayout(openErrorBoxLayout);
        openErrorBoxLayout.setHorizontalGroup(
            openErrorBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(openErrorBoxLayout.createSequentialGroup()
                .addContainerGap(83, Short.MAX_VALUE)
                .addGroup(openErrorBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dbErrorTitle)
                    .addGroup(openErrorBoxLayout.createSequentialGroup()
                        .addComponent(errorPrompt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(errorSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(84, Short.MAX_VALUE))
            .addGroup(openErrorBoxLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(errorResolve)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        openErrorBoxLayout.setVerticalGroup(
            openErrorBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(openErrorBoxLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dbErrorTitle)
                .addGap(56, 56, 56)
                .addGroup(openErrorBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(errorPrompt)
                    .addComponent(errorSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addComponent(errorResolve)
                .addContainerGap(122, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                saving(evt);
            }
        });

        dbOverview.setBackground(new java.awt.Color(255, 255, 255));

        dbLabel.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        dbLabel.setText("Database:");

        dbSelector.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        dbSelector.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select a database...", "Home Office", "Distribution Center", "Contractors", "Stores" }));
        dbSelector.setBorder(null);
        dbSelector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dbSelectorActionPerformed(evt);
            }
        });

        singleUnProUseLabel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        singleUnProUseLabel.setText("Unprocessed Users: ");

        singUnProStat.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        singleUnExUseLabel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        singleUnExUseLabel.setText("Unexported Users: ");

        singleUnExStat.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        remainingHeader.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        remainingHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        remainingHeader.setText("Totals");

        totUnProUseLabel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        totUnProUseLabel.setText("Unprocessed Users: ");

        totUnExUseLabel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        totUnExUseLabel.setText("Unexported Users: ");

        totUnExStat.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        updateTotStats();
        totUnProStat.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        javax.swing.GroupLayout dbOverviewLayout = new javax.swing.GroupLayout(dbOverview);
        dbOverview.setLayout(dbOverviewLayout);
        dbOverviewLayout.setHorizontalGroup(
            dbOverviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dbOverviewLayout.createSequentialGroup()
                .addGroup(dbOverviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dbOverviewLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(dbLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dbSelector, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(dbOverviewLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(singleUnProUseLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(singUnProStat))
                    .addGroup(dbOverviewLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(singleUnExUseLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(singleUnExStat)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(remainingHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(dbOverviewLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dbOverviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dbOverviewLayout.createSequentialGroup()
                        .addComponent(totUnProUseLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(totUnProStat))
                    .addGroup(dbOverviewLayout.createSequentialGroup()
                        .addComponent(totUnExUseLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(totUnExStat)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        dbOverviewLayout.setVerticalGroup(
            dbOverviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dbOverviewLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(dbOverviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dbLabel)
                    .addComponent(dbSelector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(dbOverviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(singleUnProUseLabel)
                    .addComponent(singUnProStat))
                .addGap(18, 18, 18)
                .addGroup(dbOverviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(singleUnExUseLabel)
                    .addComponent(singleUnExStat))
                .addGap(40, 40, 40)
                .addComponent(remainingHeader)
                .addGap(18, 18, 18)
                .addGroup(dbOverviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totUnProUseLabel)
                    .addComponent(totUnProStat))
                .addGap(18, 18, 18)
                .addGroup(dbOverviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totUnExUseLabel)
                    .addComponent(totUnExStat))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        processOverview.setBackground(new java.awt.Color(255, 255, 255));

        wpNameLab.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        wpNameLab.setText("WP Name Check");

        wpNB.setText("0%");
        wpNB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wpNBActionPerformed(evt);
            }
        });

        wpUNLab.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        wpUNLab.setText("WP Username Check");

        wpUNB.setText("0%");

        attB.setText("0%");

        ATTLab.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        ATTLab.setText("AT&T");

        notesLab.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        notesLab.setText("Notes");

        notesB.setText("0%");

        rsaLab.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        rsaLab.setText("RSA");

        rsaB.setText("0%");

        foldLab.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        foldLab.setText("Folder");

        foldB.setText("0%");

        vmB.setText("0%");

        vmLab.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        vmLab.setText("Unity");

        cmB.setText("0%");

        cmLab.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        cmLab.setText("Call Manager");

        webLab.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        webLab.setText("Webex");

        webB.setText("0%");

        rfLab.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        rfLab.setText("RightFax");

        rfB.setText("0%");

        skypeLab.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        skypeLab.setText("Skype");

        skypeB.setText("0%");

        jLabel23.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel23.setText("Processing");

        javax.swing.GroupLayout processOverviewLayout = new javax.swing.GroupLayout(processOverview);
        processOverview.setLayout(processOverviewLayout);
        processOverviewLayout.setHorizontalGroup(
            processOverviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(processOverviewLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(processOverviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel23)
                    .addGroup(processOverviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(processOverviewLayout.createSequentialGroup()
                            .addComponent(skypeLab)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(skypeB))
                        .addGroup(processOverviewLayout.createSequentialGroup()
                            .addComponent(rfLab)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rfB))
                        .addGroup(processOverviewLayout.createSequentialGroup()
                            .addComponent(webLab)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(webB))
                        .addGroup(processOverviewLayout.createSequentialGroup()
                            .addComponent(cmLab)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmB))
                        .addGroup(processOverviewLayout.createSequentialGroup()
                            .addComponent(vmLab)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(vmB))
                        .addGroup(processOverviewLayout.createSequentialGroup()
                            .addComponent(foldLab)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(foldB))
                        .addGroup(processOverviewLayout.createSequentialGroup()
                            .addComponent(rsaLab)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rsaB))
                        .addGroup(processOverviewLayout.createSequentialGroup()
                            .addComponent(notesLab)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(notesB))
                        .addGroup(processOverviewLayout.createSequentialGroup()
                            .addComponent(ATTLab)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(attB))
                        .addGroup(processOverviewLayout.createSequentialGroup()
                            .addComponent(wpNameLab)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(wpNB))
                        .addGroup(processOverviewLayout.createSequentialGroup()
                            .addComponent(wpUNLab)
                            .addGap(18, 18, 18)
                            .addComponent(wpUNB))))
                .addContainerGap(136, Short.MAX_VALUE))
        );
        processOverviewLayout.setVerticalGroup(
            processOverviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(processOverviewLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel23)
                .addGap(21, 21, 21)
                .addGroup(processOverviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(wpNameLab)
                    .addComponent(wpNB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(processOverviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(wpUNLab)
                    .addComponent(wpUNB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(processOverviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ATTLab)
                    .addComponent(attB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(processOverviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(notesLab)
                    .addComponent(notesB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(processOverviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rsaLab)
                    .addComponent(rsaB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(processOverviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(foldLab)
                    .addComponent(foldB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(processOverviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vmLab)
                    .addComponent(vmB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(processOverviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmLab)
                    .addComponent(cmB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(processOverviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(webLab)
                    .addComponent(webB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(processOverviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rfLab)
                    .addComponent(rfB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(processOverviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(skypeLab)
                    .addComponent(skypeB))
                .addContainerGap(60, Short.MAX_VALUE))
        );

        search.setBackground(new java.awt.Color(255, 255, 255));

        searchLabel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        searchLabel.setText("Search:");

        searchInput.setFont(new java.awt.Font("Calibri", 2, 18)); // NOI18N
        searchInput.setText("Search");
        searchInput.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchInputMouseClicked(evt);
            }
        });
        searchInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchInputActionPerformed(evt);
            }
        });
        searchInput.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                searchInputFocusGained(evt);
            }
        });

        searchBy.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        searchBy.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Search by..." }));
        searchBy.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                searchByFocusGained(evt);
            }
        });

        searchResult.setBackground(new java.awt.Color(255, 255, 255));

        searchSelect.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        searchSelect.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        searchResult.setViewportView(searchSelect);

        javax.swing.GroupLayout searchLayout = new javax.swing.GroupLayout(search);
        search.setLayout(searchLayout);
        searchLayout.setHorizontalGroup(
            searchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, searchLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(searchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(searchResult, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(searchBy, javax.swing.GroupLayout.Alignment.LEADING, 0, 223, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, searchLayout.createSequentialGroup()
                        .addComponent(searchLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchInput)))
                .addContainerGap())
        );
        searchLayout.setVerticalGroup(
            searchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(searchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchLabel)
                    .addComponent(searchInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(searchBy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(searchResult)
                .addContainerGap())
        );

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addComponent(dbOverview, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(processOverview, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(search, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(processOverview, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(search, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(dbOverview, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDesktopPane1.setLayer(dbOverview, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(processOverview, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(search, javax.swing.JLayeredPane.DEFAULT_LAYER);

        getContentPane().add(jDesktopPane1, java.awt.BorderLayout.CENTER);

        jMenu3.setText("File");

        openCSVOpt.setText("Load File");
        openCSVOpt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openCSVOptActionPerformed(evt);
            }
        });
        jMenu3.add(openCSVOpt);

        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        setJMenuBar(jMenuBar2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchInputMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchInputMouseClicked
        // TODO add your handling code here:
        searchInput.setText("");
        searchInput.setFont(new java.awt.Font("Calibri", 0, 18));
    }//GEN-LAST:event_searchInputMouseClicked

    /**
     * Searches database for user based on selected filter
     * @param evt 
     */
    private void searchInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchInputActionPerformed
        Object selected = searchBy.getSelectedItem();
        String find = selected.toString();
        
        ArrayList hoSearch = new ArrayList();
        ArrayList dcSearch = new ArrayList();
        ArrayList stSearch = new ArrayList();
        ArrayList coSearch = new ArrayList();
        
        if(searchInput.getSelectedText().equals(null)) {
            
        }
        else if(selected.toString().equals("Name")){
            hoSearch.addAll(ho.search(find, "name"));
            dcSearch.addAll(dc.search(find, "name"));
            stSearch.addAll(store.search(find, "name"));
            coSearch.addAll(cont.search(find, "name"));
        }
        
    }//GEN-LAST:event_searchInputActionPerformed

    private void searchInputFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchInputFocusGained
        // TODO add your handling code here:
        searchInput.setText("");
        searchInput.setFont(new java.awt.Font("Calibri", 0, 18));
    }//GEN-LAST:event_searchInputFocusGained

    private void searchByFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchByFocusGained
        //searchBy.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Username", "Full Name", "Last Name", "First Name" }));
    }//GEN-LAST:event_searchByFocusGained

    private void wpNBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wpNBActionPerformed
        // TODO add your handling code here:
        userDisplay.show(true);
    }//GEN-LAST:event_wpNBActionPerformed

    /**
     * Handles setting the current DB from the dbSelector menu
     * @param evt 
     */
    private void dbSelectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dbSelectorActionPerformed
        //Remove Select DB option
        //dbSelector.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Home Office", "Distribution Center", "Contractors", "Stores" }));
        
        //Retrieve selected option
        Object selected = dbSelector.getSelectedItem();
        
        if (selected.toString().equals("Home Office")) 
            currentDB = HOMEOFFICE;
        else if (selected.toString().equals("Distribution Center"))
            currentDB = DC;
        else if (selected.toString().equals("Contractors"))
            currentDB = CONTRACTOR;
        else if (selected.toString().equals("Stores"))
            currentDB = STORES;
        
        
        //update the stat displays
        updateSingleStats();
    }//GEN-LAST:event_dbSelectorActionPerformed

    /**
     * Saves information upon closing the main window
     * @param evt 
     */
    private void saving(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_saving
        //Saving info upon close
        ho.save(hoLoc);
        dc.save(dcLoc);
        store.save(storeLoc);
        cont.save(contLoc);
    }//GEN-LAST:event_saving

    /**
     * Opens a file from the file chooser window and adds entries to current
     *  database
     * @param evt 
     */
    private void openCSVOptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openCSVOptActionPerformed
        try {
            // TODO add your handling code here:
            int returnVal = openCSV.showOpenDialog(dbOverview);
            File file = openCSV.getSelectedFile();
            if(currentDB == HOMEOFFICE)
                ho.load(file);
            else if(currentDB == DC)
                dc.load(file);
            else if(currentDB == STORES)
                store.load(file);
            else if(currentDB == CONTRACTOR)
                cont.load(file);
            else {
                System.out.println("Error");
                openErrorBox.show(true);
                //add error; prompt to select databse to add to
            }
        } catch (IOException ex) {
            Logger.getLogger(Separator.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        updateSingleStats();
    }//GEN-LAST:event_openCSVOptActionPerformed

    /**
     * Handles the event of trying to load a file without having a database selected
     * @param evt 
     */
    private void errorSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_errorSelectActionPerformed
        // TODO add your handling code here:
        Object selected = dbSelector.getSelectedItem();
        
        if (selected.toString().equals("Home Office")) 
            currentDB = HOMEOFFICE;
        else if (selected.toString().equals("Distribution Center"))
            currentDB = DC;
        else if (selected.toString().equals("Contractors"))
            currentDB = CONTRACTOR;
        else if (selected.toString().equals("Stores"))
            currentDB = STORES;
        
        dbSelector.setSelectedItem(currentDB);
    }//GEN-LAST:event_errorSelectActionPerformed

    /**
     * 
     * @param evt 
     */
    private void errorResolveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_errorResolveActionPerformed
        Object selected = errorSelect.getSelectedItem();
        
        if (selected.toString().equals("Home Office")) {
            currentDB = HOMEOFFICE;
        }
        else if (selected.toString().equals("Distribution Center"))
            currentDB = DC;
        else if (selected.toString().equals("Contractors"))
            currentDB = CONTRACTOR;
        else if (selected.toString().equals("Stores"))
            currentDB = STORES;
        
        dbSelector.setSelectedItem(currentDB);
        
        openErrorBox.show(false);
    }//GEN-LAST:event_errorResolveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Separator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Separator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Separator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Separator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Separator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ATTLab;
    private javax.swing.JButton attB;
    private javax.swing.JButton cmB;
    private javax.swing.JLabel cmLab;
    private javax.swing.JLabel dbErrorTitle;
    private javax.swing.JLabel dbLabel;
    private javax.swing.JPanel dbOverview;
    private javax.swing.JComboBox dbSelector;
    private javax.swing.JLabel errorPrompt;
    private javax.swing.JButton errorResolve;
    private javax.swing.JComboBox errorSelect;
    private javax.swing.JButton foldB;
    private javax.swing.JLabel foldLab;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton notesB;
    private javax.swing.JLabel notesLab;
    private javax.swing.JFileChooser openCSV;
    private javax.swing.JMenuItem openCSVOpt;
    private javax.swing.JDialog openErrorBox;
    private javax.swing.JPanel processOverview;
    private javax.swing.JLabel remainingHeader;
    private javax.swing.JButton rfB;
    private javax.swing.JLabel rfLab;
    private javax.swing.JButton rsaB;
    private javax.swing.JLabel rsaLab;
    private javax.swing.JFrame rsaProcessor;
    private javax.swing.JPanel search;
    private javax.swing.JComboBox searchBy;
    private javax.swing.JTextField searchInput;
    private javax.swing.JLabel searchLabel;
    private javax.swing.JScrollPane searchResult;
    private javax.swing.JList searchSelect;
    private javax.swing.JLabel singUnProStat;
    private javax.swing.JLabel singleUnExStat;
    private javax.swing.JLabel singleUnExUseLabel;
    private javax.swing.JLabel singleUnProUseLabel;
    private javax.swing.JButton skypeB;
    private javax.swing.JLabel skypeLab;
    private javax.swing.JLabel totUnExStat;
    private javax.swing.JLabel totUnExUseLabel;
    private javax.swing.JLabel totUnProStat;
    private javax.swing.JLabel totUnProUseLabel;
    private javax.swing.JFrame userDisplay;
    private javax.swing.JButton vmB;
    private javax.swing.JLabel vmLab;
    private javax.swing.JButton webB;
    private javax.swing.JLabel webLab;
    private javax.swing.JButton wpNB;
    private javax.swing.JLabel wpNameLab;
    private javax.swing.JButton wpUNB;
    private javax.swing.JLabel wpUNLab;
    // End of variables declaration//GEN-END:variables
}
